# Generated by Django 3.2.7 on 2021-10-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttendenceManagement', '0002_auto_20210930_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_DB',
        ),
    ]
