# Generated by Django 3.2.7 on 2021-10-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendenceManagement', '0003_delete_student_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_DB',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
