# Generated by Django 4.0.1 on 2022-03-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendenceManagement', '0005_attendence_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_registration',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
